### ISSUE TITLE
fill not quite right in some gf_dist plots

### ISSUE THREAD

**Issue by homerhanumat** [ProjectMOSAIC/ggformula#113]
This works well enough:

```
x <- seq(0.25, 0.75, by = 0.01)
y <- dbeta(x, 2, 4)
df <- data.frame(x, y)
gf_dist("beta", params = list(shape1 = 2, shape2 = 4)) +
  geom_area(data = df,
            mapping = aes(x = x, y = y),
            fill = "burlywood")
```

![geom_fill](https://user-images.githubusercontent.com/5505653/46113651-40815e80-c1bd-11e8-84ab-8232d471c021.png)

But this is visibly off:

```
gf_dist("beta", params = list(shape1 = 2, shape2 = 4),
            fill = ~(x >= 0.25 & x <= 0.75),
            geom = "area")
```

![paramfill](https://user-images.githubusercontent.com/5505653/46113653-42e3b880-c1bd-11e8-8809-c8bd477f8a86.png)

**Comment by rpruim** [comment]
Actually, the second plot is doing just what ggplot2 thinks you are asking for.  So the question is whether we should add something to `gf_dist()` to make the kind of plot you want more easily.

Here's what's going on in the example above:  There are only two groups (TRUE and FALSE), and `geom_area()` doesn't treat the two tail pieces separately unless you make them different groups (you could color them the same with custom scales).  So that bit of extra "red" is part of a larger shaded region, most of which is covered by the central piece.  If we set alpha lower we can see this more clearly:

``` r
library(ggformula)
theme_set(theme_bw())
gf_dist("beta", params = list(shape1 = 2, shape2 = 4),
        fill = ~(x >= 0.25 & x <= 0.75),
        geom = "area", alpha = 0.3) 
```

![](https://i.imgur.com/CxVfevK.png)

One solution is to use `cut()` to create three groups:
``` r

gf_dist("beta", params = list(shape1 = 2, shape2 = 4),
        fill = ~cut(x, c(-Inf, 0.25, 0.75, Inf)),
        geom = "area", alpha = 0.3) 
```

![](https://i.imgur.com/CF0VIQA.png)

Created on 2018-09-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by rpruim** [comment]
One way to make things easier might be to add a `breaks` argument and have the stat create a variable that could be used for fill.  You'd still need a custom scale to get the tails to be the same color, however.

I'll have to think about whether (and how best) to implement something like this.

**Comment by rpruim** [comment]
Side note: you can avoid the use of `list()` and layer things without reverting to `+` and direct calls to geoms.

``` r
library(ggformula)
theme_set(theme_bw())
gf_dist("beta", shape1 = 2, shape2 = 4,
        fill = ~cut(x, c(-Inf, 0.25, 0.75, Inf)),
        geom = "area", alpha = 0.5)  %>%
  gf_dist("beta", shape1 = 2, shape2 = 4)
```

![](https://i.imgur.com/B7eSY71.png)

Created on 2018-09-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by homerhanumat** [comment]
Thanks, no big hurry, as my students aren't making these graphs yet.  **reprex** seems quite handy!

**Comment by rpruim** [comment]
Alternatively, you could do it this way.  As bonus you get nice labeling.  If you want to further modify the plot, be sure to use `return = "plot"`.  The default returns the probabilities as a vector, just like `pbeta()`.  This is how I have students build these plots. 

``` r
library(mosaic)
theme_set(theme_bw())
xpbeta(c(0.25, 0.75), shape1 = 2, shape2 = 4)
```

![](https://i.imgur.com/brzgN0k.png)

    #> [1] 0.3671875 0.9843750

Created on 2018-09-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by rpruim** [comment]
I'm going to close this since the behavior is as "expected", ie, just like `ggplot2`.  But I'll open a new issue about possibly adding some functionality to `gf_dist()` in the future.
