### ISSUE TITLE
gf_percents() query

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/ggformula#118]
Rebecca Andridge noted:

On Jan 4, 2019, at 3:13 PM, Andridge, Rebecca <andridge.1@osu.edu> wrote:

Hi,
 
Hopefully this is a quick question: when using the gf_percents() function to make a bar chart with 2 categorical variables, for example:
 
gf_percents( ~ bmicat | sex, data=fish)
 
what appears to get plotted are percentages of the whole sample, instead of the percentages within sex. This is unexpected behavior, at least to us, as the equivalent tally() command:
 
tally( ~ bmicat | sex, data=fish, format="percent")
 
gives the percent in each BMI category within each sex category.
 
Is this a bug? Is there a way to get the “clustered bar chart” showing the percentages within each group?
 
As a side note: we are in the process of converting our undergraduate biostatistics course from using JMP to R and are using your mosaic package – so far it seems a nice, slightly gentler, and more intuitive approach to R coding that we hope will not scare the students (many are math-phobic). Thank you!
 
Thanks,
-Rebecca

I've added a reprex.

``` r
library(mosaic)
gf_percents( ~ substance | sex, data = HELPrct); 
```

![](https://i.imgur.com/ctrIH6Q.png)

``` r
  tally(~ substance | sex, format = "percent", data = HELPrct)
#>          sex
#> substance   female     male
#>   alcohol 33.64486 40.75145
#>   cocaine 38.31776 32.08092
#>   heroin  28.03738 27.16763
```

<sup>Created on 2019-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by randridge** [comment]
Thank you -- very helpful (and I should have known it would be tricky b/c I know it's not actually easy to plot directly with ggplot).

Here's a slight modification of your suggested solution that uses the tally() function:

```
library(mosaic)
percents <- as.data.frame(tally( ~ substance | sex, data=HELPrct, format="percent")) %>% rename(Percent=Freq)
gf_col(Percent ~ substance | sex, data=percents)
```

The resulting data frame doesn't have the "perc_" prefix on the level labels and since we are teaching students to use tally() to get the conditional percentages, it seems to me that students will find it logical to take output from that function, make a DF, and the plot it. Only weird thing is the "Freq" variable name which has to be renamed to "Percent", but easy to do.
