### ISSUE TITLE
Univariate graphical modeling Y ~ 1 (?)

### ISSUE THREAD

**Issue by luebby** [ProjectMOSAIC/ggformula#131]
While, e.g. `mean(y ~ 1)` or `df_stat(y ~1)` work, e.g. `gf_histogram(y ~ 1)` won't. I think, but of course I may be mistaken, and I know that there are objections (e.g, values are on x-axis), that such an alternative to `gf_histogram( ~ x)` (same for `gf_bar()`) may help students to focus on (mosaic programming) concepts and avoid confusions about lhs vs. rhs. I feel that this might be consistent with @dtkaplan Modeling book (?).

What do you think?

**Comment by rpruim** [comment]
I'm not immediately inclined to implement this since (a) it doesn't add functionality, and (b) it doesn't really fit with the grammar of graphics via formulas approach.  One could even argue that it might be detrimental to making plots by making it less clear what the slots in the formula are for.

Of course, I also never use `mean(y ~ 1)`, even though it does fit the system (essentially the 1 is recycled into a variable with the value 1 in every position, so there is just one group, and the output is explainable within the system.)

You can, however, do 

``` r
library(ggformula)
gf_histogramh( mpg ~ ., data = mtcars)
```

![](https://i.imgur.com/aqEkjW4.png)

<sup>Created on 2019-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by luebby** [comment]
Thanks! And of course you are right. The didactical approach was just like *ok, the simplest model is without explaining variables, that is `1`. And you can do the same for graphics as with e.g. `lm()`.*

**Comment by rpruim** [comment]
Another option is to change your plot type.  For example `gf_violin(mpg ~ 1, data = mtcars)`.  But it does treat 1 like a quantitative variable and overlabel the x axis.
