### ISSUE TITLE
ggformula appears to depends on zeallot but doesn't install it

### ISSUE THREAD

**Issue by cddesja** [ProjectMOSAIC/ggformula#136]
Installing ggformula doesn't install zeallot, which it appears to depend on. This is at least the case with the version 0.9.2 on CRAN. See screenshot 

![image](https://user-images.githubusercontent.com/1608939/73303030-a6cc2600-41e3-11ea-8a3c-c93f26aa8f12.png)

**Comment by nicholasjhorton** [comment]
I've verified this problem, running 3.6.2 on Mac OS X Catalina 10.15.2

**Comment by cddesja** [comment]
Thanks for confirming. This problem still exists with the version GitHub.

I dug into the source a little bit and the only places where I can see the zeallot package is used is in the tutorials. See the screenshot.

![image](https://user-images.githubusercontent.com/1608939/73310385-3aa4ee80-41f2-11ea-8e90-4ce503523dde.png)

It looks like the package provides a single operator, `%<-%` , and hasn't been updated in 2 years and is part of r-libs. This may be an issue with some tidyverse package dependency that ggformula has, I'm guessing.

**Comment by rpruim** [comment]
That's my guess as well.  I hadn't even heard of zeallot -- so it definitely an indirect dependency.

Around this same time, 3 of the packages in the mosaic suite began throwing warnings on CRAN, so I'll be looking to see what the cause is and addressing some of the open issues before submitting ggformula, mosaic, and mosaicCore to CRAN. Just need to find some time to take care of it.

**Comment by rpruim** [comment]
I'm not sure exactly what the issue is here, but I don't think it is ours to fix.  We do not have a direct dependence on zealot, and don't want to create one just to avoid this problem.

This doesn't seem to be limited to this package.  I often have to install a dependency that is missing and try again when installing new packages.

`%<-%` by the way, is a cool thing.  It mimics behavior baked into some other programming languages.
