### ISSUE TITLE
Chaining a boxplot to a histogram for large data sets

### ISSUE THREAD

**Issue by jiyunson** [ProjectMOSAIC/ggformula#149]
Hi, it's been great to use the gf_histogram function along with gf_boxplot. Really nice for helping students develop an intuition for boxplots.

One thing we noticed is that gf_boxplot seems to have a height that is sized relatively to the y-axis. So the boxplot in using a smaller data set is thicker than one with a larger data set. 
```
# small data
gf_histogram(~ mpg, data = mtcars) %>%
gf_boxplot()
```
![image](https://user-images.githubusercontent.com/30084828/131748752-f23106e3-5d98-4aad-9698-6f9901d16121.png)

```
# slightly larger data
gf_histogram(~eruptions, data = faithful) %>%
gf_boxplot()
```
![image](https://user-images.githubusercontent.com/30084828/131749364-e37d365b-2c89-4f87-8e8a-d92529a178e6.png)

Once the data sets get very large, we don't see the boxplots (they are tiny little lines). For now we've been using the argument `width=` to adjust but often takes a little trial-and-error. 

It would be nice if the default was set differently... Thanks for considering!

**Comment by rpruim** [comment]
Sorry for my slow response.  Somehow I missed this one when it came through at the start of the semester.

For the most part, I like to stick with the ggplot2 defaults for things since that makes things more predictable (at least for those familiar with ggplot2) and it means that the ggplot2 documentation for various stats and geoms still applies to ggformula plots.

Also, it isn't clear what sort of default here would solve your problem (and also make sense in other settings).  Boxplot sizing is based on plots of just boxplots, and typically anticipate multiple side-by-side boxplots.  Each group is spaced 1 unit apart, and the size of the boxes is chosen to work in that use case.

But here is a different approach you might like.  Take a look at https://github.com/jtlandis/ggside.  I haven't built ggformula wrappers for it, and really haven't played with it much, but it is designed for placing  plots in the "margins" of other plots.
