### ISSUE TITLE
couldnt update and now cannot reinstall the package

### ISSUE THREAD

**Issue by iamYannC** [ProjectMOSAIC/ggformula#162]
Hello. I am using RStudio 2023.03.0 and R version 4.2.1 (2022-06-23 ucrt) -- "Funny-Looking Kid" on Platform: x86_64-w64-mingw32/x64 (64-bit)
```
RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
```

I tried to update the package and had a non-zero execution, so i uninstalled it and when wanted to reinstall it just didnt work. I used the installation via RStudio

This is the message i got:
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'vctrs' 0.5.2 is already loaded, but >= 0.6.0 is required
Calls: <Anonymous> ... asNamespace -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'ggformula'
* removing 'C:/Users/97253/AppData/Local/R/win-library/4.2/ggformula'
* restoring previous 'C:/Users/97253/AppData/Local/R/win-library/4.2/ggformula'
Warning in install.packages :
  installation of package ‘ggformula’ had non-zero exit status
```

and when tried to reinstall:
```
There is a binary version available but the source version
  is later:
          binary source needs_compilation
ggformula 0.10.2 0.10.4             FALSE
```

I hope I had provided all the necessary details for you to help me.

Yann

**Comment by nicholasjhorton** [comment]
Sorry for the complications.

Can you please confirm that your other packages are updated?

I've recently updated but I'm running R version 4.2.2 (2022-10-31).

**Comment by rpruim** [comment]
@iamYannC, It looks like you need a newer version of `vctrs` (and perhaps other packages).  I would start with

```{r}
detach('pkg:vctrs', character.only = TRUE)
install.packages('vctrs')
install.packages('ggformula')
```

If it has been awhile since you have updated packages, as @nicholasjhorton suggests, you might do

```{r}
update.packages()
```


The binary version of ggformula should be available on CRAN now (it can lag by 24-48 hours -- a bit longer on some of the mirrors).  If/when it is, the message about binary verse source versions will go away.

**Comment by Yann-C-INN** [comment]
Thank you.
I am on my work pc so will test your ideas later at home (over the weekend? :) ).

My other packages are up-to-date since I uninstalled 'ggformula' and then proceeded to update everything else, and it all worked. I will go through this one more time though to make sure i haven't missed anything.

**Comment by iamYannC** [comment]
My issue is with Locking AppData, which I cant find a solution to at the moment. I cant download any new packages. This is something bigger and probably in my machine, than just ggformula. Seems like ggformula is ok, the problem is with my version of R/permissions
