### ISSUE TITLE
add a version of statisticalModeling::gmodel() as gf_model?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#28]
I've not given `gmodel()` much of a test drive, but it might be useful to have something like it or like `mosaic:plotModel()` in the package.

**Comment by rpruim** [comment]
Just taking a quick look at this.  I still don't know what all it does/does not do (@dtkaplan, care to summarize?).  Things I notice:

1. It is designed to create a plot rather than a layer.  It should be pretty easy to add an `object` argument and build in chaining capability so that this plays well with the rest of `ggformula`.

2. A lot of arbitrary decisions are made without giving the user any choice (alpha levels, as one example).  Whether this is a feature or a defect isn't clear to me yet, but it seem like we could make some of these optional arguments.

@dtkaplan, should we add this essentially as is with adjustment to play with the rest of `ggformula` better, or do you already have ways you would redesign it if you were starting over?

**Comment by dtkaplan** [comment]
I like the idea of having a `gf_model()`.

I'm still trying to figure out a way to have `gmodel()` play nicely with
other layers. The problem is that `gmodel()` imposes some transformations
in order to make color and facet work for continuous variables. The result
is that adding data onto a plot (when color and facet represent continuous
variables) needs to involve applying that transformation to the data being
added. My best idea so far is to add a `show_data=` argument which would
specify a dataframe to be displayed as points but with the
quantitative->categorical transformation being applied first.

**Comment by rpruim** [comment]
Can the transformations be handled by scales?  Then new layers could simply be added and the scales would take care of transformations.  

What sorts of transformations are you talking about?  Might there be other ways to fix the problem?

**Comment by dtkaplan** [comment]
The transformation that causes the difficulty is a quantitative variable being displayed in a categorical mode in `gmodel()`. The second variable in the formula argument to `gmodel()` is represented by discrete color, the third and fourth by facetting. 

I can imagine using a continuous color scale set up to match the discrete colors displayed at the right values. So maybe that shouldn't be a problem.

But how to split the continuous variables in the third and fourth positions  so that the data points show up in the right facets? I can see how to handle this when the data are plotted within `gmodel()` (e.g. `gmodel(galton_mod, ~ mother + father + sex, plot_data = Galton)`).

**Comment by rpruim** [comment]
This is being handled as part of the ongoing improvements to `moaicModel`.  Likely `gf_model()` will live there (and be an alias to `mod_plot()`).
