### ISSUE TITLE
Name for df_stats?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#35]
This is similar to @dtkaplan's `qstats()` (but reimplemented using `aggregate()` to allow for functions that produce multiple values), but I don't see a compelling reason for the letter q.  Some options:
  * `df_stats()`: because it produces a data frame from a formula rather than a graphic from a formula.
  * `gf_stats()`: because it is in the `ggformula` package
  * `stats()`: because it is shorter

Also, we could keep or drop the final `s`.

Other options?  Preferences?

**Comment by dtkaplan** [comment]
`df_stats()` I don't like this because `df` is too generic and too similar to `gf`, which will lead to confusion.

`gf_stats()` sensible because it's in ggformula, but there's no good reason why it be in that package. The `gf` is becoming just an abstract token, unrelated to graphics. And there are so many `gf` functions, that we lose the advantage of auto-completion.

`stats()` I kind of like this because it's so concise. But I also like the `xx_` prefix approach, since that gives us a "brand" and enables auto-completion. 

Can we find another two-letter prefix that we can adopt as a brand? Some ideas ...

`ts_` for "teach statistics" (but so close to time series)
`st_` short for "statistics", so it would be `st_stats()`.
`ms_` for "mosaic" but also looks like "microsoft"
`sm_` for statistical modeling. This would be my first choice, I think.

Or, a one-letter prefix might work ...
`m_` for mosaic or modeling
`s_` for statistics
`t_` for teach
I suppose that `l_` for learn would work, but I hate to use lower-case L as an identifier: too ambiguous when read.

**Comment by rpruim** [comment]
I'm not finding any of these to really sing.
  * one-letter prefixes are too short.  There are only 26 of those (52 with caps), so name collisions are likely.
  * I agree that `ts_` and `ms_` are not so good -- they bring other things to mind
  * `st_` (statistics) is way too generic
  * `sm_` is OK except that (a) you have a package with that name and have sort of marketed that for other purposes and (b) I'm not sure this function belongs with the rest of the things that might get labeled `sm_` either.

Perhaps the first question is where this function belongs

  * in `ggformula`?
  * in `mosaic`?
  * in some other existing package?
  * in a new package (with what other features?)?

While we are talking about names -- should we have gone with `gg_point()` etc. rather than `gf_point()`?  It will be too late to change this soon, but not might not yet be.

**Comment by rpruim** [comment]
One other thought:

`f_stats()` or `f_stat()` would match some of Hadley's function names.  He uses `f_` for functions that take a formula as input, like `f_rhs()` for the right hand side of a formula.  But this is a little different, since our function uses more than just the formula, but `f_rhs()` is really just about the formula.

**Comment by rpruim** [comment]
`f_aggregate()`?  A formula version of `aggregate()`?

**Comment by nicholasjhorton** [comment]
I'm not yet hearing options that sound like a clear win (but concur that this is the right time to try to pin this down).

**Comment by rpruim** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.

-- Phil Karlton

**Comment by dtkaplan** [comment]
So many different considerations for naming ...

> `sm_` is OK except that (a) you have a package with that name and have sort of marketed that for other purposes and (b) I'm not sure this function belongs with the rest of the things that might get labeled `sm_` either.

I'm going to have to abandon the `statisticalModeling` package. It needs to stay consistent with DataCamp course and the only way to manage that is not to change the interface at all. Now I could deprecate the functions there (e.g. `effect_size()`) in favor of an `sm_` series (e.g. `sm_effect()`), but leave active the deprecated functions for the foreseeable future.

Two other ideas ...

* Put these functions into the `statPREP` package and prefix them `sp_`. That's probably a good way to start even if we can't decide.
* Create a package `smodels` or `smodeler` (both of which are available on CRAN) and use the `sm_` prefix. (There's already an `sm` package which does smoothing.

The function series I'm imagining would perhaps include:

- `sm_eval()` -- evaluate a model at specified inputs.
- `sm_train()` -- fit a model, but provide a consistent interface for a bunch of different architectures. (The `zelig` package already does this, but I'm not keen on their interface.)
- `sm_effect()` -- calculates effect sizes a la `statisticalModeling::effect_size`
- `sm_xvalidate()` for cross-validation of a model or a set of models. (`statisticalModeling::cv_pred_error()` -- horrible name -- does this the way I have in mind.
- `sm_graph()` -- or maybe just stick with the `gf_model()` idea.
- `sm_function()` -- convert a model to a function, a wrapper on `sm_eval()`
- `sm_error()` residuals for regression models, summarising them.
- `sm_likelihood()` for classifiers (or regression models)
- `sm_ensemble()` creates a bootstrap ensemble of a model which then works with any of the other - `sm_` functions.
- `sm_stats()` (maybe) instead of `qstats()` or `df_stats()`.


Proposed `gg_point()` scheme. This would make clearer the relationship to `ggplot2` and the name `ggformula`. And it works with `ggplot()` although I don't see any particular advantage.
```r
ggplot(mtcars) %>% gf_point(mpg ~ hp + color:cyl)
```

I'll ask Garrett what he thinks.

**Comment by rpruim** [comment]
>Put these functions into the statPREP package and prefix them sp_. That's probably a good way to start even if we can't decide.

I don't like using a `statPREP` package as a place for generally useful stuff.  `statPREP` won't mean much to other people, and your tendency will be to constantly throw something in at the last minute.  That's not a good place for stable code development targeted at a wider audience.

I'd save `statPREP` for things truly related to `statPREP`.

**Comment by rpruim** [comment]
@dtkaplan: Looking at your list, I think a good prefix for most of this would be `mod_` (or `model_`).  Notice that the description pretty much always mentions a model and that a model is the primary input to most of them.

I'm not sure that `df_stats()` belongs in this list -- there isn't really a model object involved.  

I think `mod` would communicate better than `sm`, and choosing a prefix that matches a package is best avoided, of possible.

That still leaves me not quite sure where `df_stats()` belongs or what it should be called.  (`prefix_summaris/ze()` would be another option for a name).

**Comment by rpruim** [comment]
I'm curious to hear what Garrett thinks (and maybe Hadley too).

**Comment by dtkaplan** [comment]
I take your point about my using `statPREP` as my `scratchPAD`. So let's eliminate that possibility.

`mod_` isn't too bad as a prefix. What package to put the `mod_` function in? `mosaic`?  `modsaic` ( a joke), `mosaicModel`? `smodels`? `models`?  Hadley has already grabbed `modelr` and it would be rude to use `modeler`. `modeling`?

**Comment by rpruim** [comment]
To me, the name of the package is less important than the names of the functions and the groups of functions that are collected in one place.  

I think `mosaic` has quite a lot in it already.  Perhaps we will eventually be back to my original idea:  `mosaic` will contain nothing and simply bring in other packages (like `tidyverse`).  The current `mosaic` might become `mosaicCore`, and there might be some movement of things out of that into other containers.  `mosaicModel` or `mosaicModels` or `mosaicModeling` might all be sufficiently good names for the `mod_` family.

We could bring `mosaicModeling` (or whatever we decide on) into conversation with the Stat2 folks who are also interested in better, simple ways to represent models.  Perhaps we can hook them on `ggformula` as well.

**Comment by rpruim** [comment]
I think this still doesn't leave us with a good name for `df_stats()`...

**Comment by dtkaplan** [comment]
How about `vstats()`? The function computes stats on a variable.

Let's go with `mosaicModel` for the `mod_` series.

**Comment by rpruim** [comment]
I've created a `mosaicModel` repository and package and copied over most of `statisticalModeling` into it (sans `ggformula` stuff).  That will give us a canvas to work with.

**Comment by rpruim** [comment]
Seems like we haven't been able to come up with a better name, so `df_stats()` it is.  I might make an alias called `df_stat()`.  I think I like the singular better.

**Comment by nicholasjhorton** [comment]
What about calc_stat()?

All the best,

Nick

**Comment by rpruim** [comment]
I'm mentally trying `calc_stat()` on for size...  Haven't decided yet.
