### ISSUE TITLE
suggestion for improving gf_dist

### ISSUE THREAD

**Issue by jiyunson** [ProjectMOSAIC/ggformula#60]
We're using ggformula for teaching introductory students statistics. We have a lot of situations where we would like students to fit a normal distribution to some univariate data. Currently we use gf_dist layered onto a gf_histogram by adding this:
%>% gf_dist("norm", color="red", params=list(mean(somevariable), sd(somevariable)))

It would be great to have an argument (such as "fitnorm") either in gf_dist (or even in the other visualizations such as gf_histogram) where the mathematical distribution was fit to the estimated parameters of some data. Thank you!

**Comment by rpruim** [comment]
I'm glad you are finding `ggformula` useful for your course, and thanks for the feedback.

Notes to self:
  * no need to restrict to normal distributions -- we can generalize to thinks that `MASS::fitdistr()` can handle pretty easily, I think.
  * adding this to `gf_histogram()` would violate the spirit of `gf_histogram()` being a lightweight wrapper around `geom_histogram()`
  * we could add a way to supply data to `gf_dist()`, but
  * perhaps it is best to create a completely new layer for this.  Perhaps an API like this:

```r
gf_histogram( ~ age, data = HELPrct) %>%
  gf_fitdistr( ~ age, data = HELPrct, dist = "normal")
```
which could be abbreviated as
```r
gf_histogram( ~ age, data = HELPrct) %>%
  gf_fitdistr(dist = "normal")
```

`gf_fitdistr()` would likely just be a wrapper around a new `geom_fitdistr()`

**Comment by dtkaplan** [comment]
[fit_distr_fun.txt](https://github.com/ProjectMOSAIC/ggformula/files/1458966/fit_distr_fun.txt)
Perhaps it would be better to leave the density fitting to functions designed specifically for that purpose.  Then arrange `gf_dens()` to accept a function of a single variable as the `dist=` argument. For instance, it could look like the following, where I've used `gf_fun()` since that already accepts a function.

```r
gf_density( ~ age, data = HELPrct) %>% 
  gf_fun(HELPrct %>% fit_distr_fun(~ age, dnorm), 
             color = "red")
```

My version of `fit_distr_fun()` is attached. (It should be a .R file, but it shows as .txt.)

**Comment by rpruim** [comment]
Some of those utilities could be handy whichever way we go with this.  

I like the option of not having to repeat the data set and formula, and I'm not sure I like specifying the distribution with  `dnorm`.   But there is also no reason we couldn't do it two ways: once where the function is created and then plotted with `gf_fun()` and once where the function is created and plotted all in one "step" -- ie, with at single function call.

**Comment by rpruim** [comment]
@dtkaplan, did you try actually using your code?  It doesn't work for me out of the box, but I got it working with a few tweaks.

However, your way of passing information to `MASS::fitdistr()` is very brittle -- you can't use `do.call()` for example and I think it will generally be problematic when nesting function calls because when you pass, for example `dnorm`, `fitdistr()` requires that it be the *name* `dnorm`, not the function named by `dnorm`.

I'm currently planning to put a version of `fit_distr_fun()` into `mosaicCore` and a custom stat into `ggformula`, so there will be two ways to do this.

**Comment by rpruim** [comment]
I have a working prototype -- probably pretty close to finalized.  To make `gf_fitdistr()` especially easy to use, I need to create a new feature for the "factory" that allows for inheritance of only specified aesthetics.  With that in place, we can now do

```r
gf_dhistogram( ~ cesd | substance,  data = HELPrct, alpha = 0.5) %>% 
  gf_fitdistr(dist = "dgamma")
```
![image](https://user-images.githubusercontent.com/722231/32693296-b47dbc60-c6f6-11e7-8cad-d5b1ecaa13c2.png)

**Comment by rpruim** [comment]
This works too,
```r
gf_dhistogram( ~ cesd | substance,  data = HELPrct, alpha = 0.5) %>% 
  gf_fun(fit_distr_fun(~cesd, data = HELPrct, dist = "dgamma"))
```
But now the function is computed using all of the data instead of separately in each panel.

![image](https://user-images.githubusercontent.com/722231/32693338-4df487fc-c6f7-11e7-898d-0f04e599e0b4.png)

**Comment by jiyunson** [comment]
gf_fitdistr() looks great. How/when can we start using this?

**Comment by jiyunson** [comment]
Also, is there a way of getting gf_fitdistr() to work with both frequency and density histograms?

**Comment by rpruim** [comment]
You can grab the code from github any time.  I expect a CRAN release in January.

I think supporting frequency histograms is likely more of a pain than it is worth, but I'll make an issue for it so the idea doesn't get lost.

**Comment by rpruim** [comment]
Thinking about this request a bit more, I think I **won't** open an issue since I think this falls into the category of psychic code -- the code would need to read your mind to do what you wanted.

The problem here is that the scaling factor isn't really determined by the layer in which the density curve is created.

For example, if you did something crazy like overlaid frequency polygons with different bin sizes, then what scaling factor should the density plot use?  Or if the density layer comes first, how is it to know what bin widths might be used in subsequent histogram layers?

In general, the density scale is just a better scale to use for this since it adheres to a reasonable "area = probability" law that defines the scale.
