### ISSUE TITLE
gf_jitter and gf_boxplot, could they use the same width?

### ISSUE THREAD

**Issue by jiyunson** [ProjectMOSAIC/ggformula#63]
Hi, we are so grateful for ggformula! It was so much harder to teach making visualizations in R AND statistical concepts at the same time before. Thank you so much for this package.

We use gf_jitter() and gf_boxplot() together and they don't seem to share the same width. For example. If we run the code below, the boxplot is thinner than the jitter. 
`gf_boxplot(age ~ substance, data = HELPrct, width = 0.2) %>%`
`gf_jitter(color = "skyblue", alpha = .5)`

Even when we put in the same value for width into jitter, boxplot is still thinner.
`gf_boxplot(age ~ substance, data = HELPrct, width = 0.2) %>%`
`gf_jitter(width = .2, color = "skyblue", alpha = .5)`
![image](https://user-images.githubusercontent.com/30084828/34911251-a082d6f8-f87b-11e7-9ca2-0f55ed1d7692.png)

It seems like the width for jitter has to be half the size of the width of boxplot (this is just from trial and error).
`gf_boxplot(age ~ substance, data = HELPrct, width = 0.4) %>%`
 `gf_jitter(width = .2, color = "skyblue", alpha = .5)`
![image](https://user-images.githubusercontent.com/30084828/34911268-ecf5af06-f87b-11e7-8bb7-8c1b34a48fb2.png)

Is there any easy to get these widths to be the same when using them together?

Thank you!

**Comment by rpruim** [comment]
This issue should really be posted on the `ggplot2` site since the right fix to get your desired behavior is for `geom_boxplot()` and `geom_jitter()` to use consistent definitions of width.  Since `ggformula` is billed as an interface to `ggplot2`, I'm not sure I want to intervene on the `ggformula` side of things.

The `width` argument appears to be undocumented in `geom_boxplot()`, but seems to give the total width of the box.  For `geom_jitter()` (really for `stat_jitter()`) it gives the maximum amount to add or subtract (that's half the width of the scatter).

@hadley, what do you think?  Does it make sense to align these?  Would it break too much old code?  At the least, could the there be some documentation explaining what `width` is in each context?

**Comment by hadley** [comment]
I suspect it's too late to align - changing the meaning of width now will change a lot of existing plots. Better documentation would be great though!

**Comment by rpruim** [comment]
@hadley, I sort of guessed you would say that.  I also had the thought of adding a second option to one or the other (say `halfwidth` added as an alternative in `geom_boxplot()`).  But then the names of the arguments would differ.

In the end, it may be that the best we can do at this point is improve the documentation.  An example overlaying jitter and boxplot with matching width (and a comment about needing one to be half the other to make them match) would be good to include.
