### ISSUE TITLE
gf_rug() fails after density-stat plots

### ISSUE THREAD

**Issue by homerhanumat** [ProjectMOSAIC/ggformula#79]
Using current version (0.6.2.9004), this works as expected:

```
gf_histogram(~ Sepal.Length, data = iris) %>% 
  gf_rug(~ Sepal.Length, data = iris)
```

But the following fails:

```
gf_dhistogram(~ Sepal.Length, data = iris) %>% 
  gf_rug(~ Sepal.Length, data = iris)

## Error in FUN(X[[i]], ...) : object 'density' not found
```

`gf_density()` followed by `gf_rug()` gives the same error.

**Comment by rpruim** [comment]
This has to do with the `..density..` aesthetic and inheritance.  So
```r
gf_dhistogram(~ Sepal.Length, data = iris) %>% 
  gf_rug(~ Sepal.Length, data = iris, inherit = FALSE)
```
will work, but your original will not because `gf_rug()` doesn't know what to do with `..density..`.

I'll have to think about whether there is a good way to make `inherit = FALSE` unnecessary.

**Comment by homerhanumat** [comment]
I see.

**Comment by rpruim** [comment]
Still not sure there is a perfect solution this.  The issue exists in the underlying `ggplot2` base, so we could consider it a feature rather than a bug.
```r
ggplot(aes(x = Sepal.Length, y = ..density..), data = iris) + geom_histogram() + geom_rug()
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## Error in FUN(X[[i]], ...) : object 'density' not found
```

This does work because the y aesthetic isn't inherited
```r
ggplot(aes(x = Sepal.Length), data = iris) + geom_histogram(aes(y = ..density..)) + geom_rug()
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

But breaks again if you try to use jitter:
```r
ggplot(aes(x = Sepal.Length), data = iris) + geom_histogram(aes(y = ..density..)) + geom_rug(position = "jitter")
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## Error: position_jitter requires the following missing aesthetics: y
## In addition: Warning messages:
## 1: In min(x, na.rm = na.rm) :
##   no non-missing arguments to min; returning Inf
## 2: In max(x, na.rm = na.rm) :
##   no non-missing arguments to max; returning -Inf
## 3: In min(diff(sort(x))) : no non-missing arguments to min; returning Inf
```

I'm going to address this (at least for now) by adding some additional examples providing ways to work around some of these features.   In the process, I've add some new behaviors as well.

**Comment by rpruim** [comment]
There may be some other options for this situation in `ggplot2` version 2.3 (coming soon).  Have to see how `stat()` works in place of `..density..`.

**Comment by rpruim** [comment]
I think a complete solution here requires writing some new geoms/positions.  So I'll leave this open for now in case there is time to implement that later.  (Or if it happens in a gg extension, we can build off that.)

For now, note that this works (but adding jitter does not because jitter requires both x and y):

```r
gf_dhistogram(~ Sepal.Length, data = iris) %>% 
   gf_rugx(~ Sepal.Length, data = iris)
```

**Comment by rpruim** [comment]
Just confirming that work on #84 has taken care of this as well -- jitter included.

``` r
suppressPackageStartupMessages(library(ggformula))
gf_dhistogram(~ Sepal.Length, data = iris) %>% 
  gf_rugx(~ Sepal.Length, data = iris, position = "jitter", alpha = 0.5, color = "red")
```

![](https://i.imgur.com/8birDHK.png)

<sup>Created on 2019-06-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
