### ISSUE TITLE
Support unquoted distribution names in gf_fitdistr()?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/ggformula#93]
library(mosaic)
gf_dhistogram(~ cesd, data = filter(HELPrct, sex == "female"), binwidth = 7.1) %>%
gf_fitdistr(dist = dnorm)

Bug? Feature? New version issue? Thanks @rpruim for any guidance.

Warning messages:
1: In if (distname %in% c("dlnorm")) { :
  the condition has length > 1 and only the first element will be used
2: In if (distname == "dnorm") { :
  the condition has length > 1 and only the first element will be used
3: In if (distname == "poisson") { :
  the condition has length > 1 and only the first element will be used
4: In if (distname == "dexp") { :
  the condition has length > 1 and only the first element will be used
5: In if (distname == "dgeom") { :
  the condition has length > 1 and only the first element will be used
6: Computation failed in `stat_fitdistr()`:
EXPR must be a length 1 vector

**Comment by rpruim** [comment]
I'll have to take a look.  It does work if you quote the function name:

``` r
library(ggformula)
library(mosaic)

gf_dhistogram(~ cesd, data = filter(HELPrct, sex == "female"), binwidth = 7.1) %>%
  gf_fitdistr(dist = "dnorm")
```

![](https://i.imgur.com/uwMtO8U.png)

Created on 2018-06-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by nicholasjhorton** [comment]
Or change the default in the function to be the quoted version...

**Comment by rpruim** [comment]
I've fixed the default and the documentation.  I'm guessing the bug was introduced when migrating to `mosaicCore::fit_distr_fun()`.

I'm not inclined to rewrite things so that the quotes are not needed since that would require more effort that it is worth just now.

``` r
library(mosaicData)
library(ggformula)
#> Loading required package: ggplot2
#> 
#> New to ggformula?  Try the tutorials: 
#>  learnr::run_tutorial("introduction", package = "ggformula")
#>  learnr::run_tutorial("refining", package = "ggformula")
theme_set(theme_bw(base_size = 5))
gf_fitdistr( ~ length, data = KidsFeet, inherit = FALSE) %>%
  gf_dhistogram( ~ length, data = KidsFeet, binwidth = 0.5, alpha = 0.25)
```

![](https://i.imgur.com/DBIkvWG.png)

``` r

gf_dhistogram( ~ length, data = KidsFeet, binwidth = 0.5, alpha = 0.25) %>%
  gf_fitdistr()
```

![](https://i.imgur.com/nH7wtqh.png)

``` r

set.seed(12345)
Dat <- data.frame(g = rgamma(500, 3, 10), f = rf(500, df1 = 3, df2 = 47))
gf_dhistogram(~g, data = Dat) %>%
  gf_fitdistr(dist = "dgamma")
```

![](https://i.imgur.com/PpWUBdD.png)

``` r

gf_dhistogram(~g, data = Dat) %>%
  gf_fun(mosaicCore::fit_distr_fun(~g, data = Dat, dist = "dgamma"))
```

![](https://i.imgur.com/1yumWSO.png)

Created on 2018-06-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by nicholasjhorton** [comment]
Thanks.  

If I'm understanding this correctly this is a change in interface.  Will there be a note on the NEWS or README.md files listing changes induced by the ggplot2.3 update?  I suspect that this would be helpful (along with the documentation updates you made to gf_fitdistr() and fit_distr_fun()

**Comment by rpruim** [comment]
It's not the kind of change you are thinking.  Originally, it was going to be like `plotDist()` and require that the distribution be specified as "norm" or "pois" or the like.  Converting to use `fit_distr_fun()` changed this to "dnorm" or "dpois" (and also allowed things like "pnorm" or "qpois").  I've edited things so that the leading "d" may be omitted.

Since `fit_distr_fun()` makes use of the name when a non-string is passed, passing something like `dnorm` through `layer_factory()` would be challenging, and it doesn't seem worth it do write a custom function that doesn't use the factory just so we can pass names.

So really, I think this is just a bug in the documentation (missing quotes).

**Comment by nicholasjhorton** [comment]
I concur.  Can this be woven into the next release?

**Comment by rpruim** [comment]
It's already there.

**Comment by nicholasjhorton** [comment]
Apologies.  I had reinstalled an hour ago and it wasn't available then.  Thanks for addressing this.

**Comment by rpruim** [comment]
Waiting for checks to complete before pushing.
